magnons:
  dir: C:\Users\Gunni002\Dropbox\UU\Magnons\Python\magnons
  save: E:\Magnons\data\main.h5

runs:
  - 
    theta: 0
    N: 400
    parallel: True
    runs:
      - 
        H: 700
      -
        H: 1000
