magnons:
  dir: C:\Users\Gunni002\Dropbox\UU\Magnons\Python\magnons
  save: E:\Magnons\data\main.h5



  
runs:
  - 
    H: 700
    theta: 0
    N: 400
    parallel: True
  - 
    H: 700
    theta: 30
    N: 400
    parallel: True
  - 
    H: 700
    theta: 60
    N: 400
    parallel: True
  - 
    H: 700
    theta: 90
    N: 400
    parallel: True
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 0
    parallel: True
    logspace: False
    ky_begin: 4
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 30
    parallel: True
    logspace: False
    ky_begin: 4
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 60
    parallel: True
    logspace: False
    ky_begin: 4
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 80
    parallel: True
    logspace: False
    ky_begin: 4