magnons:
  dir: C:\Users\Gunni002\Dropbox\UU\Magnons\Python\magnons\plot_kreisel
  save: E:\Magnons\data\main.h5

runs:
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 0
    parallel: True
    logspace: False
    ky_begin: 2
    ky_end: 6
    Nk: 32
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 30
    parallel: True
    logspace: False
    ky_begin: 2
    ky_end: 6
    Nk: 32
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 60
    parallel: True
    logspace: False
    ky_begin: 2
    ky_end: 6
    Nk: 32
  - 
    H: 2500
    theta: 0
    N: 400
    alpha: 80
    parallel: True
    logspace: False
    ky_begin: 2
    ky_end: 6
    Nk: 32