magnons:
  dir: C:\Users\Gunni002\Dropbox\UU\Magnons\Python\magnons\plot_kreisel
  save: E:\Magnons\data\main.h5

runs:
  - 
    H: 2500
    theta: 0
    N: 10
    parallel: False
    logspace: False
    ky_begin: 0.2
    ky_end: 5.3
    Nk: 16
    runs:
      -
        alpha: 0
      - 
        alpha: 30
      -
        alpha: 60
      - 
        alpha: 80