magnons:
  dir: C:\Users\Gunni002\Dropbox\UU\Magnons\Python\magnons\plot_kreisel
  save: E:\Magnons\data\main.h5

runs:
  - 
    H: 700
    N: 400
    Nk: 128
    parallel: True
    theta: [0, 30, 60, 90]